id: P000523
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:44:24.888586
source_metadata:
  id: bdr:W1KG9819
  title: ཟབ་དོན་ཐུགས་ཀྱི་སྙིང་པོ་བདུད་ཀྱི་གཅོད་ཡུལ་གྱི་སྐོར།
  author: ''
  volumes:
    ee08a54fe4984576b4a7375e78b975a3:
      image_group_id: I1KG9821
      title: Volume 1 of zab don thugs kyi snying po bdud kyi gcod yul gyi skor/
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
